-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.contactos
(
    id_mailjet bigint NOT NULL,
    email text COLLATE pg_catalog."default",
    nombre text COLLATE pg_catalog."default",
    razon_social text COLLATE pg_catalog."default",
    poblacion text COLLATE pg_catalog."default",
    provincia text COLLATE pg_catalog."default",
    codigo_isi text COLLATE pg_catalog."default",
    zona_geografica text COLLATE pg_catalog."default",
    zona_comercial text COLLATE pg_catalog."default",
    estado text COLLATE pg_catalog."default",
    centro_reparto text COLLATE pg_catalog."default",
    comercial_recambio text COLLATE pg_catalog."default",
    comercial_equipamiento text COLLATE pg_catalog."default",
    comercial_pincar text COLLATE pg_catalog."default",
    comercial_redes text COLLATE pg_catalog."default",
    coordinador_recambio text COLLATE pg_catalog."default",
    canal text COLLATE pg_catalog."default",
    tipo_cliente text COLLATE pg_catalog."default",
    red text COLLATE pg_catalog."default",
    sub_red text COLLATE pg_catalog."default",
    subcanal text COLLATE pg_catalog."default",
    division text COLLATE pg_catalog."default",
    envio_promociones text COLLATE pg_catalog."default",
    tipo_cliente_dto text COLLATE pg_catalog."default",
    activo text COLLATE pg_catalog."default",
    distribuidor text COLLATE pg_catalog."default",
    cif text COLLATE pg_catalog."default",
    telefono_1 text COLLATE pg_catalog."default",
    telefono_1_tipo text COLLATE pg_catalog."default",
    telefono_2 text COLLATE pg_catalog."default",
    telefono_2_tipo text COLLATE pg_catalog."default",
    telefono_wa text COLLATE pg_catalog."default",
    listas_mailjet text COLLATE pg_catalog."default",
    last_sync timestamp with time zone,
    distribuidor_vemare text COLLATE pg_catalog."default" DEFAULT ''::text,
    distribuidor_transcose text COLLATE pg_catalog."default" DEFAULT ''::text,
    distribuidor_dieseliberia text COLLATE pg_catalog."default" DEFAULT ''::text,
    distribuidor_paher text COLLATE pg_catalog."default" DEFAULT ''::text,
    codigo_isi_vemare text COLLATE pg_catalog."default" DEFAULT ''::text,
    codigo_isi_transcose text COLLATE pg_catalog."default" DEFAULT ''::text,
    codigo_isi_dieseliberia text COLLATE pg_catalog."default" DEFAULT ''::text,
    codigo_isi_paher text COLLATE pg_catalog."default" DEFAULT ''::text,
    CONSTRAINT contactos_pkey PRIMARY KEY (id_mailjet)
);

CREATE TABLE IF NOT EXISTS public.leads
(
    id_lead bigserial NOT NULL,
    id_mailjet bigint,
    nombre text COLLATE pg_catalog."default",
    razon_social text COLLATE pg_catalog."default",
    cif text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    telefono text COLLATE pg_catalog."default",
    area_interes text COLLATE pg_catalog."default",
    motivo text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    fecha_ultimo_contacto timestamp with time zone,
    provincia text COLLATE pg_catalog."default",
    zona character varying(100) COLLATE pg_catalog."default",
    puesto character varying(100) COLLATE pg_catalog."default",
    cv_media_id character varying(255) COLLATE pg_catalog."default",
    cv_filename character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT leads_pkey PRIMARY KEY (id_lead)
);

CREATE TABLE IF NOT EXISTS public.sesiones
(
    id_sesion bigserial NOT NULL,
    telefono text COLLATE pg_catalog."default" NOT NULL,
    estado text COLLATE pg_catalog."default",
    last_interaction_time bigint,
    expires_at bigint,
    created_at timestamp with time zone DEFAULT now(),
    waiting_for text COLLATE pg_catalog."default",
    id_mailjet bigint,
    area_interes text COLLATE pg_catalog."default",
    email_interno character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT sesiones_pkey PRIMARY KEY (id_sesion)
);

CREATE TABLE IF NOT EXISTS public.telefonos
(
    id_telefono bigserial NOT NULL,
    id_mailjet bigint,
    telefono text COLLATE pg_catalog."default" NOT NULL,
    tipo text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT telefonos_pkey PRIMARY KEY (id_telefono)
);

ALTER TABLE IF EXISTS public.leads
    ADD CONSTRAINT leads_id_mailjet_fkey FOREIGN KEY (id_mailjet)
    REFERENCES public.contactos (id_mailjet) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.sesiones
    ADD CONSTRAINT sesiones_id_mailjet_fkey FOREIGN KEY (id_mailjet)
    REFERENCES public.contactos (id_mailjet) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.telefonos
    ADD CONSTRAINT telefonos_id_mailjet_fkey FOREIGN KEY (id_mailjet)
    REFERENCES public.contactos (id_mailjet) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;