-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS contactos.contactos
(
    id_mailjet bigint NOT NULL,
    email text COLLATE pg_catalog."default",
    nombre text COLLATE pg_catalog."default",
    razon_social text COLLATE pg_catalog."default",
    poblacion text COLLATE pg_catalog."default",
    provincia text COLLATE pg_catalog."default",
    codigo_isi text COLLATE pg_catalog."default",
    zona_geografica text COLLATE pg_catalog."default",
    zona_comercial text COLLATE pg_catalog."default",
    estado text COLLATE pg_catalog."default",
    centro_reparto text COLLATE pg_catalog."default",
    comercial_recambio text COLLATE pg_catalog."default",
    comercial_equipamiento text COLLATE pg_catalog."default",
    comercial_pincar text COLLATE pg_catalog."default",
    comercial_redes text COLLATE pg_catalog."default",
    coordinador_recambio text COLLATE pg_catalog."default",
    canal text COLLATE pg_catalog."default",
    tipo_cliente text COLLATE pg_catalog."default",
    red text COLLATE pg_catalog."default",
    sub_red text COLLATE pg_catalog."default",
    subcanal text COLLATE pg_catalog."default",
    division text COLLATE pg_catalog."default",
    envio_promociones text COLLATE pg_catalog."default",
    tipo_cliente_dto text COLLATE pg_catalog."default",
    activo text COLLATE pg_catalog."default",
    distribuidor text COLLATE pg_catalog."default",
    cif text COLLATE pg_catalog."default",
    telefono_1 text COLLATE pg_catalog."default",
    telefono_1_tipo text COLLATE pg_catalog."default",
    telefono_2 text COLLATE pg_catalog."default",
    telefono_2_tipo text COLLATE pg_catalog."default",
    telefono_wa text COLLATE pg_catalog."default",
    listas_mailjet text COLLATE pg_catalog."default",
    last_sync timestamp with time zone,
    distribuidor_vemare text COLLATE pg_catalog."default" DEFAULT ''::text,
    distribuidor_transcose text COLLATE pg_catalog."default" DEFAULT ''::text,
    distribuidor_dieseliberia text COLLATE pg_catalog."default" DEFAULT ''::text,
    distribuidor_paher text COLLATE pg_catalog."default" DEFAULT ''::text,
    codigo_isi_vemare text COLLATE pg_catalog."default" DEFAULT ''::text,
    codigo_isi_transcose text COLLATE pg_catalog."default" DEFAULT ''::text,
    codigo_isi_dieseliberia text COLLATE pg_catalog."default" DEFAULT ''::text,
    codigo_isi_paher text COLLATE pg_catalog."default" DEFAULT ''::text,
    CONSTRAINT contactos_pkey PRIMARY KEY (id_mailjet)
);
END;