-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS inbound.leads
(
    id_lead bigserial NOT NULL,
    id_mailjet bigint,
    nombre text COLLATE pg_catalog."default",
    razon_social text COLLATE pg_catalog."default",
    cif text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    telefono text COLLATE pg_catalog."default",
    area_interes text COLLATE pg_catalog."default",
    motivo text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    fecha_ultimo_contacto timestamp with time zone,
    provincia text COLLATE pg_catalog."default",
    zona character varying(100) COLLATE pg_catalog."default",
    puesto character varying(100) COLLATE pg_catalog."default",
    cv_media_id character varying(255) COLLATE pg_catalog."default",
    cv_filename character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT leads_pkey PRIMARY KEY (id_lead)
);

CREATE TABLE IF NOT EXISTS inbound.sesiones
(
    id_sesion bigserial NOT NULL,
    telefono text COLLATE pg_catalog."default" NOT NULL,
    estado text COLLATE pg_catalog."default",
    last_interaction_time bigint,
    expires_at bigint,
    created_at timestamp with time zone DEFAULT now(),
    waiting_for text COLLATE pg_catalog."default",
    id_mailjet bigint,
    area_interes text COLLATE pg_catalog."default",
    email_interno character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT sesiones_pkey PRIMARY KEY (id_sesion)
);

CREATE TABLE IF NOT EXISTS inbound.telefonos
(
    id_telefono bigserial NOT NULL,
    id_mailjet bigint,
    telefono text COLLATE pg_catalog."default" NOT NULL,
    tipo text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT telefonos_pkey PRIMARY KEY (id_telefono)
);
END;