-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS maestro.empresas_distribuidoras
(
    id_empresa_distribuidora bigserial NOT NULL,
    codigo_empresa character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nombre_empresa character varying(255) COLLATE pg_catalog."default" NOT NULL,
    activa boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT empresas_distribuidoras_pkey PRIMARY KEY (id_empresa_distribuidora),
    CONSTRAINT empresas_distribuidoras_codigo_empresa_key UNIQUE (codigo_empresa)
);

CREATE TABLE IF NOT EXISTS maestro.encuestas_maestro
(
    id_encuesta bigserial NOT NULL,
    codigo_encuesta character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_fase_experiencia bigint NOT NULL,
    interaccion_activa boolean NOT NULL DEFAULT true,
    id_externo_encuesta character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT encuestas_maestro_pkey PRIMARY KEY (id_encuesta),
    CONSTRAINT encuestas_maestro_codigo_encuesta_key UNIQUE (codigo_encuesta)
);

CREATE TABLE IF NOT EXISTS maestro.encuestas_metricas_config
(
    id_encuesta bigint NOT NULL,
    id_metrica bigint NOT NULL,
    peso_global_marketing numeric(10, 4) NOT NULL DEFAULT 1.0000,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_encuestas_metricas_config PRIMARY KEY (id_encuesta, id_metrica)
);

CREATE TABLE IF NOT EXISTS maestro.encuestas_versiones
(
    id_encuesta_version bigserial NOT NULL,
    id_encuesta bigint NOT NULL,
    version_num integer NOT NULL,
    version_encuesta character varying(50) COLLATE pg_catalog."default" NOT NULL,
    version_activa boolean NOT NULL DEFAULT false,
    fecha_creacion timestamp without time zone NOT NULL DEFAULT now(),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT encuestas_versiones_pkey PRIMARY KEY (id_encuesta_version),
    CONSTRAINT uq_encuesta_version_num UNIQUE (id_encuesta, version_num)
);

CREATE TABLE IF NOT EXISTS maestro.fases_experiencia
(
    id_fase_experiencia bigserial NOT NULL,
    codigo_fase character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    activa boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT fases_experiencia_pkey PRIMARY KEY (id_fase_experiencia),
    CONSTRAINT fases_experiencia_codigo_fase_key UNIQUE (codigo_fase)
);

CREATE TABLE IF NOT EXISTS maestro.lista_metricas
(
    id_metrica bigserial NOT NULL,
    codigo_metrica character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default",
    valores_escala character varying(50) COLLATE pg_catalog."default",
    formula_calculo text COLLATE pg_catalog."default",
    activa boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT lista_metricas_pkey PRIMARY KEY (id_metrica),
    CONSTRAINT lista_metricas_codigo_metrica_key UNIQUE (codigo_metrica)
);

CREATE TABLE IF NOT EXISTS maestro.opciones_maestro
(
    id_opcion bigserial NOT NULL,
    codigo_opcion character varying(150) COLLATE pg_catalog."default" NOT NULL,
    id_pregunta bigint NOT NULL,
    texto_opcion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    valor_numerico numeric(10, 2) NOT NULL,
    id_externo_opcion character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT opciones_maestro_pkey PRIMARY KEY (id_opcion),
    CONSTRAINT opciones_maestro_codigo_opcion_key UNIQUE (codigo_opcion),
    CONSTRAINT uq_opcion_valor_por_pregunta UNIQUE (id_pregunta, valor_numerico)
);

CREATE TABLE IF NOT EXISTS maestro.origenes_encuesta
(
    id_origen bigserial NOT NULL,
    codigo_origen character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT origenes_encuesta_pkey PRIMARY KEY (id_origen),
    CONSTRAINT origenes_encuesta_codigo_origen_key UNIQUE (codigo_origen)
);

CREATE TABLE IF NOT EXISTS maestro.ponderaciones_versiones
(
    id_ponderacion_version bigserial NOT NULL,
    id_encuesta bigint NOT NULL,
    version_num integer NOT NULL,
    id_pregunta bigint NOT NULL,
    id_metrica bigint NOT NULL,
    peso_global_marketing numeric(10, 4) NOT NULL,
    peso_final_calculado numeric(10, 4) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT ponderaciones_versiones_pkey PRIMARY KEY (id_ponderacion_version),
    CONSTRAINT uq_pv_encuesta_version_pregunta UNIQUE (id_encuesta, version_num, id_pregunta)
);

CREATE TABLE IF NOT EXISTS maestro.preguntas_maestro
(
    id_pregunta bigserial NOT NULL,
    codigo_pregunta character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_encuesta bigint NOT NULL,
    id_metrica bigint NOT NULL,
    orden integer NOT NULL,
    texto_pregunta text COLLATE pg_catalog."default" NOT NULL,
    pregunta_activa boolean NOT NULL DEFAULT true,
    id_externo_pregunta character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT preguntas_maestro_pkey PRIMARY KEY (id_pregunta),
    CONSTRAINT preguntas_maestro_codigo_pregunta_key UNIQUE (codigo_pregunta),
    CONSTRAINT uq_pregunta_orden_por_encuesta UNIQUE (id_encuesta, orden)
);

CREATE TABLE IF NOT EXISTS maestro.tipos_interaccion
(
    id_tipo_interaccion bigserial NOT NULL,
    codigo_tipo_interaccion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT tipos_interaccion_pkey PRIMARY KEY (id_tipo_interaccion),
    CONSTRAINT tipos_interaccion_codigo_tipo_interaccion_key UNIQUE (codigo_tipo_interaccion)
);

ALTER TABLE IF EXISTS maestro.encuestas_maestro
    ADD CONSTRAINT fk_encuestas_fase FOREIGN KEY (id_fase_experiencia)
    REFERENCES maestro.fases_experiencia (id_fase_experiencia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS maestro.encuestas_metricas_config
    ADD CONSTRAINT fk_emc_encuesta FOREIGN KEY (id_encuesta)
    REFERENCES maestro.encuestas_maestro (id_encuesta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS maestro.encuestas_metricas_config
    ADD CONSTRAINT fk_emc_metrica FOREIGN KEY (id_metrica)
    REFERENCES maestro.lista_metricas (id_metrica) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS maestro.encuestas_versiones
    ADD CONSTRAINT fk_versiones_encuesta FOREIGN KEY (id_encuesta)
    REFERENCES maestro.encuestas_maestro (id_encuesta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uq_encuestas_versiones_activa
    ON maestro.encuestas_versiones(id_encuesta);


ALTER TABLE IF EXISTS maestro.opciones_maestro
    ADD CONSTRAINT fk_opciones_pregunta FOREIGN KEY (id_pregunta)
    REFERENCES maestro.preguntas_maestro (id_pregunta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS maestro.ponderaciones_versiones
    ADD CONSTRAINT fk_pv_encuesta FOREIGN KEY (id_encuesta)
    REFERENCES maestro.encuestas_maestro (id_encuesta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS maestro.ponderaciones_versiones
    ADD CONSTRAINT fk_pv_metrica FOREIGN KEY (id_metrica)
    REFERENCES maestro.lista_metricas (id_metrica) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS maestro.ponderaciones_versiones
    ADD CONSTRAINT fk_pv_pregunta FOREIGN KEY (id_pregunta)
    REFERENCES maestro.preguntas_maestro (id_pregunta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS maestro.ponderaciones_versiones
    ADD CONSTRAINT fk_pv_version FOREIGN KEY (id_encuesta, version_num)
    REFERENCES maestro.encuestas_versiones (id_encuesta, version_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS maestro.preguntas_maestro
    ADD CONSTRAINT fk_preguntas_encuesta FOREIGN KEY (id_encuesta)
    REFERENCES maestro.encuestas_maestro (id_encuesta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS maestro.preguntas_maestro
    ADD CONSTRAINT fk_preguntas_metrica FOREIGN KEY (id_metrica)
    REFERENCES maestro.lista_metricas (id_metrica) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;