-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ejecuciones_encuesta
(
    id_ejecucion bigserial NOT NULL,
    id_encuesta bigint NOT NULL,
    id_tipo_interaccion bigint NOT NULL,
    id_origen bigint NOT NULL,
    id_empresa_distribuidora bigint NOT NULL,
    id_externo_collector character varying(255) COLLATE pg_catalog."default",
    titulo_ejecucion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    es_prueba boolean NOT NULL DEFAULT false,
    fecha_inicio_envio timestamp without time zone,
    fecha_fin_envio timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT ejecuciones_encuesta_pkey PRIMARY KEY (id_ejecucion),
    CONSTRAINT uq_ejecucion_contexto UNIQUE (id_encuesta, id_tipo_interaccion, id_origen, id_empresa_distribuidora, es_prueba)
);

CREATE TABLE IF NOT EXISTS public.encuestas_envios
(
    id_envio bigserial NOT NULL,
    id_ejecucion bigint NOT NULL,
    id_externo_envio character varying(255) COLLATE pg_catalog."default",
    codigo_isi character varying(100) COLLATE pg_catalog."default",
    destinatario character varying(255) COLLATE pg_catalog."default",
    fecha_envio timestamp without time zone,
    atributos_adicionales jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT encuestas_envios_pkey PRIMARY KEY (id_envio)
);

CREATE TABLE IF NOT EXISTS public.respuestas
(
    id_respuesta bigserial NOT NULL,
    id_ejecucion bigint NOT NULL,
    id_envio bigint,
    id_encuesta bigint NOT NULL,
    version_num integer NOT NULL,
    id_pregunta bigint NOT NULL,
    id_grupo_respuesta uuid NOT NULL,
    codigo_isi character varying(100) COLLATE pg_catalog."default",
    id_metrica bigint NOT NULL,
    peso_final_calculado numeric(10, 4) NOT NULL,
    valor_numerico numeric(10, 2),
    valor_calculado numeric(10, 4),
    respuesta_comentario text COLLATE pg_catalog."default",
    atributos_adicionales jsonb,
    fecha_respuesta timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT respuestas_pkey PRIMARY KEY (id_respuesta)
);

ALTER TABLE IF EXISTS public.encuestas_envios
    ADD CONSTRAINT fk_envios_ejecucion FOREIGN KEY (id_ejecucion)
    REFERENCES public.ejecuciones_encuesta (id_ejecucion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.respuestas
    ADD CONSTRAINT fk_respuestas_ejecucion FOREIGN KEY (id_ejecucion)
    REFERENCES public.ejecuciones_encuesta (id_ejecucion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.respuestas
    ADD CONSTRAINT fk_respuestas_envio FOREIGN KEY (id_envio)
    REFERENCES public.encuestas_envios (id_envio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;