-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS encuestas.encuestas_wa_config
(
    id serial NOT NULL,
    codigo_encuesta text COLLATE pg_catalog."default" NOT NULL,   -- = maestro.encuestas_maestro.codigo_encuesta, sin FK (propiedad de TI)
    flow_id text COLLATE pg_catalog."default",
    template_name text COLLATE pg_catalog."default",
    wa_media_id_cache text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT encuestas_wa_config_pkey PRIMARY KEY (id),
    CONSTRAINT encuestas_wa_config_codigo_encuesta_key UNIQUE (codigo_encuesta)
);

CREATE TABLE IF NOT EXISTS encuestas.campanas_wa
(
    id serial NOT NULL,
    codigo_encuesta text COLLATE pg_catalog."default" NOT NULL,
    version_num integer,
    codigo_empresa text COLLATE pg_catalog."default" NOT NULL,
    id_externo_collector text COLLATE pg_catalog."default",
    titulo_campana text COLLATE pg_catalog."default" NOT NULL,
    es_prueba boolean NOT NULL DEFAULT false,
    modo_envio text COLLATE pg_catalog."default",
    segmento_filtro text COLLATE pg_catalog."default",
    template_name text COLLATE pg_catalog."default",
    flow_id text COLLATE pg_catalog."default",
    wa_media_id text COLLATE pg_catalog."default",
    estado text COLLATE pg_catalog."default" NOT NULL DEFAULT 'BORRADOR'::text,
    total_enviados integer NOT NULL DEFAULT 0,
    fecha_inicio_envio timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT campanas_wa_pkey PRIMARY KEY (id),
    CONSTRAINT campanas_wa_id_externo_collector_key UNIQUE (id_externo_collector)
);

CREATE TABLE IF NOT EXISTS encuestas.empresas_wa
(
    id serial NOT NULL,
    codigo_empresa text COLLATE pg_catalog."default" NOT NULL,
    phone_number_id text COLLATE pg_catalog."default" NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT empresas_wa_pkey PRIMARY KEY (id),
    CONSTRAINT empresas_wa_codigo_empresa_key UNIQUE (codigo_empresa)
);

CREATE TABLE IF NOT EXISTS encuestas.envios_wa
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_campana integer NOT NULL,
    codigo_isi text COLLATE pg_catalog."default",
    razon_social text COLLATE pg_catalog."default",
    telefono_wa text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default",
    wa_flow_token uuid NOT NULL DEFAULT gen_random_uuid(),
    wa_message_id text COLLATE pg_catalog."default",
    estado_envio text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDIENTE'::text,
    estado_entrega text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDIENTE'::text,
    ts_envio timestamp without time zone,
    ts_delivered timestamp without time zone,
    ts_read timestamp without time zone,
    intentos integer NOT NULL DEFAULT 0,
    error_msg text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT envios_wa_pkey PRIMARY KEY (id),
    CONSTRAINT envios_wa_wa_flow_token_key UNIQUE (wa_flow_token),
    CONSTRAINT uq_envio_campana_telefono UNIQUE (id_campana, telefono_wa)
);

CREATE TABLE IF NOT EXISTS encuestas.respuestas_wa
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_campana integer NOT NULL,
    id_envio uuid NOT NULL,
    codigo_encuesta text COLLATE pg_catalog."default" NOT NULL,
    version_num integer NOT NULL,
    codigo_pregunta text COLLATE pg_catalog."default" NOT NULL,
    codigo_metrica text COLLATE pg_catalog."default" NOT NULL,
    codigo_isi text COLLATE pg_catalog."default",
    razon_social text COLLATE pg_catalog."default",
    id_grupo_respuesta uuid NOT NULL,
    peso_final_calculado numeric(10, 4) NOT NULL DEFAULT 0,
    valor_numerico numeric(10, 2),
    valor_calculado numeric(10, 4),
    respuesta_comentario text COLLATE pg_catalog."default",
    atributos_adicionales jsonb,
    fecha_respuesta timestamp without time zone NOT NULL DEFAULT now(),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT respuestas_wa_pkey PRIMARY KEY (id),
    CONSTRAINT uq_respuesta_grupo_pregunta UNIQUE (id_grupo_respuesta, codigo_pregunta)
);

ALTER TABLE IF EXISTS encuestas.envios_wa
    ADD CONSTRAINT envios_wa_id_campana_fkey FOREIGN KEY (id_campana)
    REFERENCES encuestas.campanas_wa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_envios_campana
    ON encuestas.envios_wa(id_campana);


ALTER TABLE IF EXISTS encuestas.respuestas_wa
    ADD CONSTRAINT respuestas_wa_id_campana_fkey FOREIGN KEY (id_campana)
    REFERENCES encuestas.campanas_wa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_respuestas_campana
    ON encuestas.respuestas_wa(id_campana);


ALTER TABLE IF EXISTS encuestas.respuestas_wa
    ADD CONSTRAINT respuestas_wa_id_envio_fkey FOREIGN KEY (id_envio)
    REFERENCES encuestas.envios_wa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

END;